from app.models.auth import (
    Device,
    EmailChangeToken,
    EmailVerificationToken,
    OAuthAccount,
    PasswordResetToken,
    RefreshToken,
)
from app.models.base import Base
from app.models.enums import (
    BookingStatus,
    ChecklistKind,
    DevicePlatform,
    ExpenseCategory,
    LinkProvider,
    LinkTargetType,
    MembershipRole,
    OAuthProvider,
    PhotoStatus,
    PhotoTargetType,
    PlaceProvider,
    Procurement,
    RelationshipType,
    SensitiveAction,
    RevokeReason,
    ReservationStatus,
    ReservationTargetType,
    ScheduleItemType,
    SplitMode,
    TagScope,
    ThrottleScope,
    TransportDirection,
    TransportMethod,
    TripPlaceStatus,
    TripStatus,
    UserStatus,
)
from app.models.cooking import Checklist, ChecklistItem, Ingredient, Recipe
from app.models.expense import Expense, ExpenseShare, Payment
from app.models.memory import AuditLog, Diary, Memo, Photo, PhotoLink
from app.models.oauth import OAuthPendingLogin, OAuthState
from app.models.reauth import ReauthProof
from app.models.place import Place, TripPlace
from app.models.schedule import Reservation, ScheduleItem, Stay, Transport
from app.models.space import (
    INVITE_DAYS,
    INVITE_MAX_USES,
    MAX_MEMBERS_PER_SPACE,
    Membership,
    RelationshipProfile,
    Space,
    SpaceInvite,
)
from app.models.throttle import ThrottleCounter
from app.models.tag import ExternalLink, Tag, Tagging
from app.models.trip import Trip, TripDay, TripParticipant
from app.models.user import User

# alembic 이 autogenerate 할 때 여기 없는 모델은 보지 못한다.
# 새 모델을 만들면 반드시 이 목록에 추가한다.
__all__ = [
    "INVITE_DAYS",
    "INVITE_MAX_USES",
    "MAX_MEMBERS_PER_SPACE",
    "AuditLog",
    "Base",
    "BookingStatus",
    "Checklist",
    "ChecklistItem",
    "ChecklistKind",
    "Device",
    "DevicePlatform",
    "Diary",
    "Expense",
    "ExpenseCategory",
    "ExpenseShare",
    "ExternalLink",
    "LinkProvider",
    "Ingredient",
    "LinkTargetType",
    "Membership",
    "MembershipRole",
    "Memo",
    "OAuthAccount",
    "OAuthPendingLogin",
    "OAuthProvider",
    "OAuthState",
    "PasswordResetToken",
    "EmailChangeToken",
    "Payment",
    "Photo",
    "PhotoLink",
    "PhotoStatus",
    "PhotoTargetType",
    "Place",
    "PlaceProvider",
    "Procurement",
    "RelationshipProfile",
    "ReauthProof",
    "Recipe",
    "RefreshToken",
    "RelationshipType",
    "Reservation",
    "ReservationStatus",
    "ReservationTargetType",
    "RevokeReason",
    "ScheduleItem",
    "ScheduleItemType",
    "SensitiveAction",
    "Space",
    "SpaceInvite",
    "SplitMode",
    "Stay",
    "Tag",
    "TagScope",
    "Tagging",
    "ThrottleCounter",
    "ThrottleScope",
    "Transport",
    "TransportDirection",
    "TransportMethod",
    "Trip",
    "TripDay",
    "TripParticipant",
    "TripPlace",
    "TripPlaceStatus",
    "TripStatus",
    "User",
    "UserStatus",
]
