"""memos, diaries, photos and audit logs

Revision ID: 01ba46b8367a
Revises: ced31a1cd876
Create Date: 2026-09-14 17:05:24.903831
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '01ba46b8367a'
down_revision: str | None = 'ced31a1cd876'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('uploader_membership_id', sa.UUID(), nullable=True),
    sa.Column('original_path', sa.String(length=500), nullable=True),
    sa.Column('display_path', sa.String(length=500), nullable=True),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('caption', sa.String(length=200), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('original_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('uploading', 'ready', 'restricted', 'deleted', 'failed', name='photostatus', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('height IS NULL OR height > 0', name=op.f('ck_photos_height_positive')),
    sa.CheckConstraint('original_bytes IS NULL OR original_bytes > 0', name=op.f('ck_photos_bytes_positive')),
    sa.CheckConstraint('width IS NULL OR width > 0', name=op.f('ck_photos_width_positive')),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_photos_trip_id_trips'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploader_membership_id'], ['memberships.id'], name=op.f('fk_photos_uploader_membership_id_memberships'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_photos'))
    )
    op.create_index('ix_photos_checksum', 'photos', ['checksum'], unique=False)
    op.create_index('ix_photos_trip_status', 'photos', ['trip_id', 'status'], unique=False)
    op.create_table('photo_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('photo_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.Enum('trip', 'day', 'place', 'schedule', 'stay', name='phototargettype', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], name=op.f('fk_photo_links_photo_id_photos'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_photo_links'))
    )
    op.create_index('ix_photo_links_target', 'photo_links', ['target_type', 'target_id'], unique=False)
    op.create_index('uq_photo_links_target', 'photo_links', ['photo_id', 'target_type', 'target_id'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('space_id', sa.UUID(), nullable=True),
    sa.Column('actor_membership_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=True),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_membership_id'], ['memberships.id'], name=op.f('fk_audit_logs_actor_membership_id_memberships'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], name=op.f('fk_audit_logs_space_id_spaces'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_space_time', 'audit_logs', ['space_id', 'created_at'], unique=False)
    op.create_index('ix_audit_logs_target', 'audit_logs', ['target_type', 'target_id'], unique=False)
    op.create_table('diaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('author_membership_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=60), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('written_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['author_membership_id'], ['memberships.id'], name=op.f('fk_diaries_author_membership_id_memberships'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_diaries_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_diaries_trip_id_trips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diaries'))
    )
    op.create_index('ix_diaries_trip_day', 'diaries', ['trip_id', 'written_on'], unique=False)
    op.create_table('memos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('author_membership_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('deleted_at IS NOT NULL OR deleted_by IS NULL', name=op.f('ck_memos_deleted_by_needs_time')),
    sa.ForeignKeyConstraint(['author_membership_id'], ['memberships.id'], name=op.f('fk_memos_author_membership_id_memberships'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_memos_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['deleted_by'], ['memberships.id'], name=op.f('fk_memos_deleted_by_memberships'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_memos_trip_id_trips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memos'))
    )
    op.create_index('ix_memos_trip_alive', 'memos', ['trip_id', 'deleted_at'], unique=False)
    op.add_column('expenses', sa.Column('receipt_photo_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_expenses_receipt_photo_id_photos'), 'expenses', 'photos', ['receipt_photo_id'], ['id'], ondelete='SET NULL')
    op.add_column('trips', sa.Column('cover_photo_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_trips_cover_photo_id_photos'), 'trips', 'photos', ['cover_photo_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_trips_cover_photo_id_photos'), 'trips', type_='foreignkey')
    op.drop_column('trips', 'cover_photo_id')
    op.drop_constraint(op.f('fk_expenses_receipt_photo_id_photos'), 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'receipt_photo_id')
    op.drop_index('ix_memos_trip_alive', table_name='memos')
    op.drop_table('memos')
    op.drop_index('ix_diaries_trip_day', table_name='diaries')
    op.drop_table('diaries')
    op.drop_index('ix_audit_logs_target', table_name='audit_logs')
    op.drop_index('ix_audit_logs_space_time', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('uq_photo_links_target', table_name='photo_links')
    op.drop_index('ix_photo_links_target', table_name='photo_links')
    op.drop_table('photo_links')
    op.drop_index('ix_photos_trip_status', table_name='photos')
    op.drop_index('ix_photos_checksum', table_name='photos')
    op.drop_table('photos')
    # ### end Alembic commands ###
