"""expenses, shares and payments

Revision ID: 11f448ccb6e2
Revises: f5d9dcef82bd
Create Date: 2026-09-14 16:49:30.025540
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '11f448ccb6e2'
down_revision: str | None = 'f5d9dcef82bd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('from_membership_id', sa.UUID(), nullable=False),
    sa.Column('to_membership_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('amount > 0', name=op.f('ck_payments_amount_positive')),
    sa.CheckConstraint('from_membership_id <> to_membership_id', name=op.f('ck_payments_from_is_not_to')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_payments_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_membership_id'], ['memberships.id'], name=op.f('fk_payments_from_membership_id_memberships'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['to_membership_id'], ['memberships.id'], name=op.f('fk_payments_to_membership_id_memberships'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_payments_trip_id_trips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index('ix_payments_trip_alive', 'payments', ['trip_id', 'deleted_at'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('trip_day_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=60), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('category', sa.Enum('meal', 'transport', 'lodging', 'admission', 'shopping', 'other', name='expensecategory', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('payer_membership_id', sa.UUID(), nullable=False),
    sa.Column('split_mode', sa.Enum('even', 'subset', 'amount', name='splitmode', native_enum=False, create_constraint=True, length=20), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('amount > 0', name=op.f('ck_expenses_amount_positive')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_expenses_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payer_membership_id'], ['memberships.id'], name=op.f('fk_expenses_payer_membership_id_memberships'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trip_day_id'], ['trip_days.id'], name=op.f('fk_expenses_trip_day_id_trip_days'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_expenses_trip_id_trips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expenses'))
    )
    op.create_index('ix_expenses_trip', 'expenses', ['trip_id'], unique=False)
    op.create_index('ix_expenses_trip_day', 'expenses', ['trip_day_id'], unique=False)
    op.create_table('expense_shares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('expense_id', sa.UUID(), nullable=False),
    sa.Column('membership_id', sa.UUID(), nullable=False),
    sa.Column('weight', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('weight >= 0', name=op.f('ck_expense_shares_weight_not_negative')),
    sa.ForeignKeyConstraint(['expense_id'], ['expenses.id'], name=op.f('fk_expense_shares_expense_id_expenses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], name=op.f('fk_expense_shares_membership_id_memberships'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expense_shares'))
    )
    op.create_index('uq_expense_shares_member', 'expense_shares', ['expense_id', 'membership_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_expense_shares_member', table_name='expense_shares')
    op.drop_table('expense_shares')
    op.drop_index('ix_expenses_trip_day', table_name='expenses')
    op.drop_index('ix_expenses_trip', table_name='expenses')
    op.drop_table('expenses')
    op.drop_index('ix_payments_trip_alive', table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
