"""throttle counters and reauth proofs

Revision ID: 5ae20e7a4185
Revises: 6aca97e40bd2
Create Date: 2026-09-14 17:28:30.488998
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '5ae20e7a4185'
down_revision: str | None = '6aca97e40bd2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('throttle_counters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.Enum('login', 'signup', 'email_verification', 'password_reset', name='throttlescope', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('window_started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('attempts >= 0', name=op.f('ck_throttle_counters_attempts_not_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_throttle_counters'))
    )
    op.create_index('ix_throttle_window', 'throttle_counters', ['window_started_at'], unique=False)
    op.create_index('uq_throttle_scope_key', 'throttle_counters', ['scope', 'key_hash'], unique=True)
    op.create_table('reauth_proofs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('delete_account', 'change_email', 'change_password', 'link_provider', 'unlink_provider', name='sensitiveaction', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reauth_proofs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reauth_proofs'))
    )
    op.create_index('ix_reauth_proofs_user', 'reauth_proofs', ['user_id', 'action'], unique=False)
    op.create_index('uq_reauth_proofs_hash', 'reauth_proofs', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_reauth_proofs_hash', table_name='reauth_proofs')
    op.drop_index('ix_reauth_proofs_user', table_name='reauth_proofs')
    op.drop_table('reauth_proofs')
    op.drop_index('uq_throttle_scope_key', table_name='throttle_counters')
    op.drop_index('ix_throttle_window', table_name='throttle_counters')
    op.drop_table('throttle_counters')
    # ### end Alembic commands ###
