"""auth: devices, refresh tokens and one-time links

Revision ID: 6aca97e40bd2
Revises: 01ba46b8367a
Create Date: 2026-09-14 17:10:11.230759
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '6aca97e40bd2'
down_revision: str | None = '01ba46b8367a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('installation_id', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.Enum('ios', 'android', 'web', 'unknown', name='deviceplatform', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('app_version', sa.String(length=20), nullable=True),
    sa.Column('display_name', sa.String(length=40), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_devices_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_devices'))
    )
    op.create_index('ix_devices_user_seen', 'devices', ['user_id', 'last_seen_at'], unique=False)
    op.create_index('uq_devices_installation', 'devices', ['user_id', 'installation_id'], unique=True)
    op.create_table('email_verification_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_email_verification_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_verification_tokens'))
    )
    op.create_index('ix_email_verification_tokens_user', 'email_verification_tokens', ['user_id'], unique=False)
    op.create_index('uq_email_verification_tokens_hash', 'email_verification_tokens', ['token_hash'], unique=True)
    op.create_table('oauth_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('google', 'apple', 'kakao', 'naver', name='oauthprovider', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('provider_subject', sa.String(length=255), nullable=False),
    sa.Column('provider_email', sa.String(length=320), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_oauth_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_accounts'))
    )
    op.create_index('ix_oauth_accounts_user', 'oauth_accounts', ['user_id'], unique=False)
    op.create_index('uq_oauth_accounts_subject', 'oauth_accounts', ['provider', 'provider_subject'], unique=True)
    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens'))
    )
    op.create_index('ix_password_reset_tokens_user', 'password_reset_tokens', ['user_id'], unique=False)
    op.create_index('uq_password_reset_tokens_hash', 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('token_family_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('replaced_by', sa.UUID(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.Enum('rotated', 'reuse_detected', 'logout', 'password_reset', 'device_limit', 'admin', name='revokereason', native_enum=False, create_constraint=True, length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_refresh_tokens_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['replaced_by'], ['refresh_tokens.id'], name=op.f('fk_refresh_tokens_replaced_by_refresh_tokens'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index('ix_refresh_tokens_family', 'refresh_tokens', ['token_family_id'], unique=False)
    op.create_index('ix_refresh_tokens_user_alive', 'refresh_tokens', ['user_id', 'revoked_at'], unique=False)
    op.create_index('uq_refresh_tokens_hash', 'refresh_tokens', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_refresh_tokens_hash', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_user_alive', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_family', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('uq_password_reset_tokens_hash', table_name='password_reset_tokens')
    op.drop_index('ix_password_reset_tokens_user', table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index('uq_oauth_accounts_subject', table_name='oauth_accounts')
    op.drop_index('ix_oauth_accounts_user', table_name='oauth_accounts')
    op.drop_table('oauth_accounts')
    op.drop_index('uq_email_verification_tokens_hash', table_name='email_verification_tokens')
    op.drop_index('ix_email_verification_tokens_user', table_name='email_verification_tokens')
    op.drop_table('email_verification_tokens')
    op.drop_index('uq_devices_installation', table_name='devices')
    op.drop_index('ix_devices_user_seen', table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
