"""trips, days and participants

Revision ID: 87739dc0fe92
Revises: ffa430cdf967
Create Date: 2026-09-14 16:23:13.009534
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '87739dc0fe92'
down_revision: str | None = 'ffa430cdf967'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('space_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=False),
    sa.Column('region_code', sa.String(length=20), nullable=True),
    sa.Column('region_name', sa.String(length=40), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('planning', 'ongoing', 'completed', 'archived', name='tripstatus', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('cooking_enabled', sa.Boolean(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('budget', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('simplify_settlement', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deletion_scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('budget IS NULL OR budget >= 0', name=op.f('ck_trips_budget_not_negative')),
    sa.CheckConstraint('end_date >= start_date', name=op.f('ck_trips_dates_in_order')),
    sa.CheckConstraint('exchange_rate IS NULL OR exchange_rate > 0', name=op.f('ck_trips_exchange_rate_positive')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_trips_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], name=op.f('fk_trips_space_id_spaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trips'))
    )
    op.create_index('ix_trips_space_start_date', 'trips', ['space_id', 'start_date'], unique=False)
    op.create_table('trip_days',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('day_index >= 1', name=op.f('ck_trip_days_day_index_positive')),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_trip_days_trip_id_trips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_days'))
    )
    op.create_index('uq_trip_days_date', 'trip_days', ['trip_id', 'date'], unique=True)
    op.create_index('uq_trip_days_index', 'trip_days', ['trip_id', 'day_index'], unique=True)
    op.create_table('trip_participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('membership_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_trip_participants_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], name=op.f('fk_trip_participants_membership_id_memberships'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_trip_participants_trip_id_trips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_participants'))
    )
    op.create_index('uq_trip_participants_active', 'trip_participants', ['trip_id', 'membership_id'], unique=True, postgresql_where='removed_at IS NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_trip_participants_active', table_name='trip_participants', postgresql_where='removed_at IS NULL')
    op.drop_table('trip_participants')
    op.drop_index('uq_trip_days_index', table_name='trip_days')
    op.drop_index('uq_trip_days_date', table_name='trip_days')
    op.drop_table('trip_days')
    op.drop_index('ix_trips_space_start_date', table_name='trips')
    op.drop_table('trips')
    # ### end Alembic commands ###
