"""places, tags and external links

Revision ID: b35408f6471a
Revises: 87739dc0fe92
Create Date: 2026-09-14 16:37:39.397817
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'b35408f6471a'
down_revision: str | None = '87739dc0fe92'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('places',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=8, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('provider', sa.Enum('naver', 'kakao', 'manual', name='placeprovider', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('provider_place_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(latitude IS NULL) = (longitude IS NULL)', name=op.f('ck_places_coordinates_together')),
    sa.CheckConstraint('latitude IS NULL OR (latitude >= -90 AND latitude <= 90)', name=op.f('ck_places_latitude_in_range')),
    sa.CheckConstraint('longitude IS NULL OR (longitude >= -180 AND longitude <= 180)', name=op.f('ck_places_longitude_in_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_places'))
    )
    op.create_index('uq_places_provider_place', 'places', ['provider', 'provider_place_id'], unique=True, postgresql_where='provider_place_id IS NOT NULL')
    op.create_table('external_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.Enum('trip', 'place', 'schedule', 'stay', name='linktargettype', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('naver_map', 'kakao_map', 'youtube', 'booking', 'other', name='linkprovider', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_external_links_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_links'))
    )
    op.create_index('ix_external_links_target', 'external_links', ['target_type', 'target_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('space_id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.Enum('place', 'packing', 'ingredient', name='tagscope', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_tags_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], name=op.f('fk_tags_space_id_spaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags'))
    )
    op.create_index('uq_tags_space_scope_name', 'tags', ['space_id', 'scope', 'name'], unique=True)
    op.create_table('taggings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.Enum('place', 'packing', 'ingredient', name='tagscope', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_taggings_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_taggings'))
    )
    op.create_index('ix_taggings_target', 'taggings', ['target_type', 'target_id'], unique=False)
    op.create_index('uq_taggings_target', 'taggings', ['tag_id', 'target_type', 'target_id'], unique=True)
    op.create_table('trip_places',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('status', sa.Enum('saved', 'scheduled', 'visited', name='tripplacestatus', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('area', sa.String(length=30), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_trip_places_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_trip_places_place_id_places'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_trip_places_trip_id_trips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_places'))
    )
    op.create_index('ix_trip_places_trip_status', 'trip_places', ['trip_id', 'status'], unique=False)
    op.create_index('uq_trip_places_place', 'trip_places', ['trip_id', 'place_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_trip_places_place', table_name='trip_places')
    op.drop_index('ix_trip_places_trip_status', table_name='trip_places')
    op.drop_table('trip_places')
    op.drop_index('uq_taggings_target', table_name='taggings')
    op.drop_index('ix_taggings_target', table_name='taggings')
    op.drop_table('taggings')
    op.drop_index('uq_tags_space_scope_name', table_name='tags')
    op.drop_table('tags')
    op.drop_index('ix_external_links_target', table_name='external_links')
    op.drop_table('external_links')
    op.drop_index('uq_places_provider_place', table_name='places', postgresql_where='provider_place_id IS NOT NULL')
    op.drop_table('places')
    # ### end Alembic commands ###
