"""checklists, recipes and ingredients

Revision ID: ced31a1cd876
Revises: 11f448ccb6e2
Create Date: 2026-09-14 16:53:43.507373
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'ced31a1cd876'
down_revision: str | None = '11f448ccb6e2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.Enum('packing', 'shopping', name='checklistkind', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_checklists_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_checklists_trip_id_trips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checklists'))
    )
    op.create_index('ix_checklists_trip', 'checklists', ['trip_id', 'kind'], unique=False)
    op.create_table('recipes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('servings IS NULL OR servings > 0', name=op.f('ck_recipes_servings_positive')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_recipes_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_recipes_trip_id_trips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipes'))
    )
    op.create_index('ix_recipes_trip', 'recipes', ['trip_id', 'sort_order'], unique=False)
    op.create_table('ingredients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('quantity', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('procurement', sa.Enum('bring', 'buy', 'undecided', name='procurement', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('owner_membership_id', sa.UUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("procurement = 'bring' OR owner_membership_id IS NULL", name=op.f('ck_ingredients_owner_only_when_bringing')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_ingredients_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_membership_id'], ['memberships.id'], name=op.f('fk_ingredients_owner_membership_id_memberships'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name=op.f('fk_ingredients_recipe_id_recipes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingredients'))
    )
    op.create_index('ix_ingredients_recipe', 'ingredients', ['recipe_id', 'sort_order'], unique=False)
    op.create_table('checklist_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('checklist_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('quantity', sa.String(length=20), nullable=True),
    sa.Column('owner_membership_id', sa.UUID(), nullable=True),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by', sa.UUID(), nullable=True),
    sa.Column('source_ingredient_id', sa.UUID(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('NOT is_shared OR owner_membership_id IS NULL', name=op.f('ck_checklist_items_shared_has_no_owner')),
    sa.CheckConstraint('completed_at IS NOT NULL OR completed_by IS NULL', name=op.f('ck_checklist_items_completed_by_needs_time')),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], name=op.f('fk_checklist_items_checklist_id_checklists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['completed_by'], ['memberships.id'], name=op.f('fk_checklist_items_completed_by_memberships'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_checklist_items_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_membership_id'], ['memberships.id'], name=op.f('fk_checklist_items_owner_membership_id_memberships'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_ingredient_id'], ['ingredients.id'], name=op.f('fk_checklist_items_source_ingredient_id_ingredients'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checklist_items'))
    )
    op.create_index('ix_checklist_items_list', 'checklist_items', ['checklist_id', 'sort_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_checklist_items_list', table_name='checklist_items')
    op.drop_table('checklist_items')
    op.drop_index('ix_ingredients_recipe', table_name='ingredients')
    op.drop_table('ingredients')
    op.drop_index('ix_recipes_trip', table_name='recipes')
    op.drop_table('recipes')
    op.drop_index('ix_checklists_trip', table_name='checklists')
    op.drop_table('checklists')
    # ### end Alembic commands ###
