"""schedule, stays, transports and reservations

Revision ID: f5d9dcef82bd
Revises: b35408f6471a
Create Date: 2026-09-14 16:43:45.007293
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f5d9dcef82bd'
down_revision: str | None = 'b35408f6471a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.Enum('place', 'stay', 'other', name='reservationtargettype', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=60), nullable=False),
    sa.Column('party_size', sa.Integer(), nullable=True),
    sa.Column('reserved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('confirmed', 'needs_check', 'cancelled', name='reservationstatus', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('booking_url', sa.String(length=2048), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('show_in_schedule', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('party_size IS NULL OR party_size > 0', name=op.f('ck_reservations_party_size_positive')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_reservations_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_reservations_trip_id_trips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservations'))
    )
    op.create_index('ix_reservations_target', 'reservations', ['target_type', 'target_id'], unique=False)
    op.create_index('ix_reservations_trip', 'reservations', ['trip_id', 'reserved_at'], unique=False)
    op.create_table('transports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('owner_membership_id', sa.UUID(), nullable=True),
    sa.Column('direction', sa.Enum('outbound', 'return', name='transportdirection', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('method', sa.Enum('ktx', 'srt', 'bus', 'flight', 'other', name='transportmethod', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('departure_name', sa.String(length=40), nullable=True),
    sa.Column('departure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('arrival_name', sa.String(length=40), nullable=True),
    sa.Column('arrival_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('booking_status', sa.Enum('booked', 'not_booked', name='bookingstatus', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('show_in_schedule', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('arrival_at IS NULL OR departure_at IS NULL OR arrival_at >= departure_at', name=op.f('ck_transports_arrival_after_departure')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_transports_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_membership_id'], ['memberships.id'], name=op.f('fk_transports_owner_membership_id_memberships'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_transports_trip_id_trips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transports'))
    )
    op.create_index('ix_transports_trip', 'transports', ['trip_id', 'departure_at'], unique=False)
    op.create_table('schedule_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('trip_day_id', sa.UUID(), nullable=True),
    sa.Column('trip_place_id', sa.UUID(), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('title', sa.String(length=60), nullable=False),
    sa.Column('type', sa.Enum('place', 'meal', 'move', 'rest', 'other', name='scheduleitemtype', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('end_at IS NULL OR start_at IS NULL OR end_at >= start_at', name=op.f('ck_schedule_items_times_in_order')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_schedule_items_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_day_id'], ['trip_days.id'], name=op.f('fk_schedule_items_trip_day_id_trip_days'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_schedule_items_trip_id_trips'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_place_id'], ['trip_places.id'], name=op.f('fk_schedule_items_trip_place_id_trip_places'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_items'))
    )
    op.create_index('ix_schedule_items_day', 'schedule_items', ['trip_day_id', 'sort_order'], unique=False)
    op.create_table('stays',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('trip_place_id', sa.UUID(), nullable=True),
    sa.Column('check_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('has_kitchen', sa.Boolean(), nullable=True),
    sa.Column('booking_url', sa.String(length=2048), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('show_in_schedule', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('check_out_at IS NULL OR check_in_at IS NULL OR check_out_at > check_in_at', name=op.f('ck_stays_checkout_after_checkin')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_stays_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_stays_trip_id_trips'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_place_id'], ['trip_places.id'], name=op.f('fk_stays_trip_place_id_trip_places'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stays'))
    )
    op.create_index('ix_stays_trip', 'stays', ['trip_id', 'check_in_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stays_trip', table_name='stays')
    op.drop_table('stays')
    op.drop_index('ix_schedule_items_day', table_name='schedule_items')
    op.drop_table('schedule_items')
    op.drop_index('ix_transports_trip', table_name='transports')
    op.drop_table('transports')
    op.drop_index('ix_reservations_trip', table_name='reservations')
    op.drop_index('ix_reservations_target', table_name='reservations')
    op.drop_table('reservations')
    # ### end Alembic commands ###
