"""oauth states and pending logins

Revision ID: fa90b80b73f2
Revises: a93d5e27c1b8
Create Date: 2026-09-15 14:22:06.364030
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'fa90b80b73f2'
down_revision: str | None = 'a93d5e27c1b8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_pending_logins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('google', 'apple', 'kakao', 'naver', name='oauthprovider', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('provider_subject', sa.String(length=255), nullable=False),
    sa.Column('provider_email', sa.String(length=320), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=True),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('code_challenge', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('link_token_hash', sa.String(length=64), nullable=True),
    sa.Column('link_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_pending_logins'))
    )
    op.create_index('ix_oauth_pending_logins_expires', 'oauth_pending_logins', ['expires_at'], unique=False)
    op.create_index('uq_oauth_pending_logins_code', 'oauth_pending_logins', ['code_hash'], unique=True)
    op.create_index('uq_oauth_pending_logins_link', 'oauth_pending_logins', ['link_token_hash'], unique=True, postgresql_where='link_token_hash IS NOT NULL')
    op.create_table('oauth_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('google', 'apple', 'kakao', 'naver', name='oauthprovider', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('state_hash', sa.String(length=64), nullable=False),
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('app_redirect_uri', sa.String(length=200), nullable=False),
    sa.Column('app_state', sa.String(length=128), nullable=False),
    sa.Column('code_challenge', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_states'))
    )
    op.create_index('ix_oauth_states_expires', 'oauth_states', ['expires_at'], unique=False)
    op.create_index('uq_oauth_states_hash', 'oauth_states', ['state_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_oauth_states_hash', table_name='oauth_states')
    op.drop_index('ix_oauth_states_expires', table_name='oauth_states')
    op.drop_table('oauth_states')
    op.drop_index('uq_oauth_pending_logins_link', table_name='oauth_pending_logins', postgresql_where='link_token_hash IS NOT NULL')
    op.drop_index('uq_oauth_pending_logins_code', table_name='oauth_pending_logins')
    op.drop_index('ix_oauth_pending_logins_expires', table_name='oauth_pending_logins')
    op.drop_table('oauth_pending_logins')
    # ### end Alembic commands ###
